---
- name: Create directory
  file: path=/var/www/{{ domain }} state=directory owner=www-data group=www-data

- name: Create index.html
  template: src=template/index.j2 dest=/var/www/{{ domain}}/index.html

