---
- hosts: all
  become: true
  vars_files:
    - roles/nginx/vars/main.yml   
  vars: 
    utils : 
      - vim
    domain : test.local

  roles: 
    - name: utils 
      tags : 
        - utils 

    - name: nginx 
      tags: 
        - nginx
