---
- hosts: all
  become: true
  vars:
    utils :
      - vim
    domain : drupal-test
    php:
      - php5
      - php5-gd
      - php5-mysqlnd
      - php5-json
      - php5-curl
#    drupal_version :
#      - 8.3.0

  roles:
    - name: utils
      tags :
        - utils

    - name: apache
      tags:
        - apache
    - name: drupal
      tags:
        - drupal
    - name: mysql
      tags:
        - mysql
