---
  - name: download - drupal
    get_url: url="https://ftp.drupal.org/files/projects/drupal-8.3.0.tar.gz" dest=/tmp mode=0440

  - name: Unzip de drupal
    unarchive:
      src: /tmp/drupal-8.3.0.tar.gz
      dest: /var/www/{{domain}}
      remote_src:  True
      mode: 0775
      owner: www-data
      group: www-data
  - name: Copie du fichier settings.php
    copy:
      src: "/var/www/{{domain}}/drupal-8.3.0/sites/default/default.settings.php"
      dest: "/var/www/{{domain}}/drupal-8.3.0/sites/default/settings.php"
      mode: 0664
      owner: www-data
      group: www-data
      remote_src: True
